baseURL = "https://su-record.github.io/"
# languageCode = "en-us"
title = "Su record"
theme = "hugo-PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
disqusShortname = "su-record"

[minify]
disableXML = true
minifyOutput = true

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "su all life"
author = "Su"
ShowReadingTime = true
defaultTheme = "auto"
ShowShareButtons = true
comments = true

[params.assets]
disableFingerprinting = true

[params.profileMode]
enabled = true
title = "늦어도 괜찮아 멈추지 말자"
imageUrl = "#"
imageTitle = "my image"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/su-record/writing"

  [[params.profileMode.buttons]]
  name = "Tags"
  url = "tags"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
